### ISSUE TITLE
Update Jenkinsfile to new format

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/autopush-integration-tests#65]
see:
https://github.com/Kinto/kinto-integration-tests/blob/master/Jenkinsfile

**Comment by stephendonner** [comment]
We'll have to move this repo to either the "mozilla" or "mozilla-services" GitHub account/namespace, due to https://github.com/mozilla/fxtest-jenkins-pipeline/blob/c1e22572071172418cf5bff389ba3ffea0cd8119/src/org/mozilla/fxtest/ServiceBook.groovy#L31-L40, before the Service Book integration will work (just as a reminder).

**Comment by rpappalax** [comment]
@stephendonner yea, i recall that all of our tests ultimately need to reside there before being Jenkins-friendly (for that reason).  however, i'd like to get at least 1 or 2 tests working properly and then i'll xfer ownership over to mozilla-services org.  thx for the reminder!
